name: Publish Redis RPM

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: Private release tag
        required: true
        default: redis-8.8.0-el10
      asset_name:
        description: Exact RPM filename
        required: true
        default: redis-8.8.0-1.el10.x86_64.rpm

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group